export type Flower = {
  slug: string
  name: string
  description: string
  image: string
  fobPrice?: string
  minOrder?: string
  supplyAbility?: string
  port?: string
  paymentTerms?: string
  details?: Record<string, string>
  productDescription?: string
  packagingShipping?: string
}

export const flowers: Flower[] = [
  {
    slug: "asiatic-lily-bunch",
    name: "Asiatic Lily - Bunch",
    description: "Beautiful, vibrant Asiatic lilies in perfect bunches",
    image: "/assets/flowers/Asiatic-Lily.jpg",
    fobPrice: " - ",
    minOrder: "500 Pieces",
    supplyAbility: " - ",
    port: "Chennai",
    paymentTerms: "	100% TT in advance",
    productDescription: "Asiatic Lily is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packed in ventilated flower boxes with water-absorbent gel. Shipped in climate-controlled containers by air freight for optimal freshness. Each bunch contains 10 stems.",
    //details: { "Product Type": "Asiatic Lily", "Style": "Fresh Cut Flowers", "Size": "60-90 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g per bunch", "Place Origin": "India", "Vase Life": "10-14 days", "Stems Per Bunch": "10" },
  },
  {
    slug: "carnation-bunch",
    name: "Carnation - Bunch",
    description: "Fresh, long-lasting carnations for all occasions",
    image: "/assets/flowers/Carnation.jpg",
    fobPrice: " - ",
    minOrder: "500 Pieces",
    supplyAbility: " - ",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A rose is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    //details: { "Product Type": "Carnation", "Style": "Fresh Cut Flowers", "Size": "50-70 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "600g per bunch", "Place Origin": "India", "Vase Life": "21-28 days", "Stems Per Bunch": "20-25" },
  },
  {
    slug: "fresh-jasmine",
    name: "Fresh Jasmine Cut Flowers Exporters to All Countries",
    description: "Premium jasmine flowers exported worldwide",
    image: "/assets/flowers/jasmine.jpg",
    fobPrice: "US$80.00 – US$150.00 Per Thermocole Box",
    minOrder: "10 Boxes",
    supplyAbility: "100 Boxes per week",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: `We are fresh jasmine flowers supplier and exporter.
    We are specialized in Supplying: Loose Buds & Strings and Garlands ( Maala ).
    We have decided to the team to pack the jasmine flowers and to ship the cargo to customer destination with mentioned timings.`,
    packagingShipping: "Packed in ventilated boxes to maintain freshness and fragrance. Air freight shipping ensures quick delivery to international markets. Available in bunches of 50-100 stems.",
    details: { "Product Type": "Jasmine Flower", "Style": "Fresh Cut Flowers", "Size": "1-3 cm ", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Color": "White", "Model Number": "CF-JS-002" },
  },
  {
    slug: "fresh-lotus",
    name: "Fresh Lotus Exporters",
    description: "Fresh lotus flowers for traditional and modern arrangements",
    image: "/assets/flowers/lotus-flower.jpg",
    fobPrice: "US $0.1-0.3 / Piece",
    minOrder: "500 Pieces",
    supplyAbility: "5000 pieces per week",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: `We are fresh lotus cut flowers supplier and exporter.
        We are specialized in Supplying: Loose Buds and Garlands (Maalai).
        We have decided to the team to pack the lotus flowers and to ship the cargo to customer destination with mentioned timings.`,
    packagingShipping: "Packaging : Thermocol boxes [14-17 kg per box] , Delivery Time: 1 day after payment",
    details: { "Product Type": "Lotus Flower", "Style": "Fresh Cut Flowers", "Size": "10 cm ", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "5 kg", "Place Origin": "India", "Varieties": "Pink", "Model Number": "CF-LS-001" },
  },
  {
    slug: "fresh-rose-cut-flowers",
    name: "Fresh Rose Cut Flowers",
    description: "Premium quality rose cut flowers in various colors",
    image: "/assets/flowers/rose-cut-flower.jpg",
    fobPrice: "US 0.5 $ – 1.5 $",
    minOrder: "500 kg",
    supplyAbility: "1000 Kilogram per day",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A rose is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: `Packaging Details: Thermocol boxes [14-17 kg per box] ,
                        Delivery Time: 2 days.`,
    details: { "Product Type": "Rose", "Style": "Fresh Cut Flowers", "Size": "5-7 cm", "Grade": "A+", "Certification": " FF-MGY-004", "Weight": "500g", "Place Origin": "India", "Colors Available": "Red", "Model Number": "CF-JS-001" },
  },
  {
    slug: "yellow-marigold",
    name: "Fresh Yellow Marigold Cut Flowers",
    description: "Vibrant yellow marigolds fresh from the farm",
    image: "/assets/flowers/Marigold.jpg",
    fobPrice: " US $ 0.50 - $ 1.5 ",
    minOrder: "500 kg",
    supplyAbility: "1000 kilogram per day",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: `Marigolds are hardy, annual plants and are great plants for cheering up any garden. Broadly, there are two genuses which are referred to by the common name, Marigolds viz. Tagetes and Calendula. 
    Marigolds come in different colors, yellow and orange being the most common. Most of the marigolds have strong, pungent odor and have great value in cosmetic treatment. There are many varieties of Marigolds available today.`,
    packagingShipping: `Packaging Details: Thermocol boxes [14-17 kg per box] , 
                        Delivery Time: 2 days`,
    details: { "Product Type": "Marigold", "Style": "Fresh Cut Flowers", "Size": "5-7 cm", "Grade": "A", "Certification": "FF-MGY-004", "Weight": "500g ", "Place Origin": "India", "Color": "Yellow", "Model Number": "CF-JS-001" },
  },
  {
    slug: "gerbera-bunch",
    name: "Gerbara - Bunch",
    description: "Colorful and cheerful gerbera flowers in bunches",
    image: "/assets/flowers/Gerbara.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Gerbara is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box] ",
    //details: { "Product Type": "Gerbera", "Style": "Fresh Cut Flowers", "Size": "6-7 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g ", "Place Origin": "India", "Bloom Size": "8-12 cm", "Vase Life": "14-20 days" },
  },
  {
    slug: "gypsophila-bunch",
    name: "Gypsophila - Bunch",
    description: "Delicate gypsophila perfect as filler flowers",
    image: "/assets/flowers/Gypsophila.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Gypsophila is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    //details: { "Product Type": "Gypsophila", "Style": "Fresh Cut Flowers", "Size": "5-7 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Color": "White", "Vase Life": "14-21 days" },
  },
  {
    slug: "jasmine-exporters",
    name: "Jasmine Flower Exporters",
    description: "Fragrant jasmine flowers for export markets",
    image: "/assets/flowers/jasmine.jpg",
    fobPrice: "US$80.00 – US$150.00 Per Thermocole Box",
    minOrder: "10 Boxes",
    supplyAbility: "100 Boxes per Week",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: `We are fresh jasmine flowers supplier and exporter.
    We are specialized in Supplying: Loose Buds & Strings and Garlands ( Maala ).
    We have decided to the team to pack the jasmine flowers and to ship the cargo to customer destination with mentioned timings.`,
    packagingShipping: `Jasmine Packing Details :
    Jasmine Loose Flower : 15 Kg Per Thermocole Box
    Jasmine Strings : 350 to 400 Feet Per Thermocole Box`,
    details: { "Product Type": "Jasmine Flower", "Style": "Fresh Cut Flowers", "Size": "1-3 cm blooms", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Fragrance": "Natural Strong", "Model Number": "CF-JS-001" },
  },
  {
    slug: "lotus-cut-flowers",
    name: "Lotus Cut Flowers",
    description: "Fresh cut lotus flowers with premium quality",
    image: "/assets/flowers/lotus-flower.jpg",
    fobPrice: "US $0.1-0.3 / Piece",
    minOrder: "500 pieces",
    supplyAbility: "5000 pieces per week",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: `We are fresh lotus cut flowers supplier and exporter.
    We are specialized in Supplying: Loose Buds and Garlands (Maala).
    We have decided to the team to pack the lotus flowers and to ship the cargo to customer destination with mentioned timings.`,
    packagingShipping: `Packaging Details: Thermocol boxes &
    Delivery Time: 1 day after payment , Packing:
    Thermocol boxes [14-17 kg per box]`,
    details: { "Product Type": "Lotus Flower", "Style": "Fresh Cut Flowers", "Size": "10 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "5 Kg", "Place Origin": "India", "Color": "Pink", "Model Number": "CF-LS-003" },
  },
  {
    slug: "orchid-blue-bunch",
    name: "Orchid Blue - Bunch",
    description: "Stunning blue orchids in beautiful bunches",
    image: "/assets/flowers/Orchid-Blue.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Orchid Blue is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Orchid Blue", "Style": "Fresh Cut Flowers", "Size": "5 - 6 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g per bunch", "Place Origin": "India", "Bloom Size": "5-7 cm", "Vase Life": "20-25 days" },
  },
  {
    slug: "orchid-pink-bunch",
    name: "Orchid Pink - Bunch",
    description: "Elegant pink orchids perfect for arrangements",
    image: "/assets/flowers/Orchid-pink.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Orchid Pink is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Orchid Pink", "Style": "Fresh Cut Flowers", "Size": "6-8 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Bloom Size": "5-7 cm", "Vase Life": "20-25 days" },
  },
  {
    slug: "orchid-white-bunch",
    name: "Orchid White - Bunch",
    description: "Pure white orchids of the highest quality",
    image: "/assets/flowers/Orchid-White.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Orchid White is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Orchid White", "Style": "Fresh Cut Flowers", "Size": "6-8 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g ", "Place Origin": "India", "Bloom Size": "5-7 cm", "Vase Life": "20-25 days" },
  },
  {
    slug: "orchids-purple-bunch",
    name: "Orchids Purple - Bunch",
    description: "Majestic purple orchids in premium bunches",
    image: "/assets/flowers/Orchids-Purple.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Orchids Purple is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Orchid Purple", "Style": "Fresh Cut Flowers", "Size": "6 - 8 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Bloom Size": "5-7 cm", "Vase Life": "20-25 days" },
  },
  {
    slug: "oriental-lily-bunch",
    name: "Oriental Lily - Bunch",
    description: "Fragrant and stunning Oriental lilies",
    image: "/assets/flowers/Oriental-Lily.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Oriental Lily is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Oriental Lily", "Style": "Fresh Cut Flowers", "Size": "6-9 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g ", "Place Origin": "India", "Bloom Size": "12-15 cm", "Vase Life": "10-14 days" },
  },
  {
    slug: "rajnigandha-bunch",
    name: "Rajnigandha - Bunch",
    description: "Sweet-scented Rajnigandha flowers in bunches",
    image: "/assets/flowers/Rajnigandha.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Rajnigandha is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box].",
    // details: { "Product Type": "Rajnigandha", "Style": "Fresh Cut Flowers", "Size": "4-5 cm", "Grade": "A", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Fragrance": "Sweet Natural", "Vase Life": "7-10 days" },
  },
  {
    slug: "rose-color-bunch",
    name: "Rose Color - Bunch",
    description: "Colorful roses in beautiful mixed bunches",
    image: "/assets/flowers/Rose-Color.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Rose Color is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Rose Mixed", "Style": "Fresh Cut Flowers", "Size": "6-9 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Colors": "Red, Pink, Yellow, White, Coral, Orange", "Vase Life": "14-21 days" },
  },
  {
    slug: "rose-red-bunch",
    name: "Rose Red - Bunch",
    description: "Classic red roses of premium quality",
    image: "/assets/flowers/Rose-Red.jpg",
    fobPrice: "-",
    minOrder: "500 Pieces",
    supplyAbility: "-",
    port: "Chennai",
    paymentTerms: "100% TT in advance",
    productDescription: "A Rose Red is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles.",
    packagingShipping: "Packing: Thermocol boxes [14-17 kg per box]",
    // details: { "Product Type": "Rose Red", "Style": "Fresh Cut Flowers", "Size": "6-9 cm", "Grade": "A+", "Certification": "Plant Quarantine / Fumigation", "Weight": "500g", "Place Origin": "India", "Color": "Deep Red", "Vase Life": "14-21 days" },
  },
]

export default flowers
